#!/bin/bash
# zcode-for-agents 安装脚本
# 职责：skills 的分发交给 `npx skills add dej4vu/zcode-for-agents -g`（vercel-labs/skills），
#       本脚本只做 skills CLI 做不了的事：
#         1. 创建 ~/.local/bin/zcode wrapper（ZCode CLI 随桌面 App 分发，不在 PATH）
#         2. （可选）向 ~/.codex/AGENTS.md 与 ~/.claude/CLAUDE.md 注入指针段
# 幂等：可重复执行。
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${HOME}/.local/bin"
WRAPPER="${BIN_DIR}/zcode"
MARKER_START="<!-- zcode-for-agents:start -->"
MARKER_END="<!-- zcode-for-agents:end -->"

WITH_POINTERS=1
for arg in "$@"; do
  case "$arg" in
    --no-pointers) WITH_POINTERS=0 ;;
    -h|--help) echo "用法: install.sh [--no-pointers]"; exit 0 ;;
    *) echo "未知参数: $arg" >&2; exit 1 ;;
  esac
done

echo "==> 1/4 探测 ZCode CLI (zcode.cjs)"
OS="$(uname -s)"
ZCODE_CJS=""
ZCODE_BIN=""

if [[ "$OS" == "Darwin" ]]; then
  ZCODE_CJS="$(ls /Applications/ZCode.app/Contents/Resources/*/zcode.cjs 2>/dev/null | head -n1 || true)"
  [[ -z "$ZCODE_CJS" ]] && ZCODE_CJS="$(ls ~/Applications/ZCode.app/Contents/Resources/*/zcode.cjs 2>/dev/null | head -n1 || true)"
  if [[ -n "$ZCODE_CJS" ]]; then
    ZCODE_BIN="${ZCODE_CJS%/Contents/Resources*}/Contents/MacOS/ZCode"
    [[ -x "$ZCODE_BIN" ]] || ZCODE_BIN="/Applications/ZCode.app/Contents/MacOS/ZCode"
  fi
elif [[ "$OS" == "Linux" ]]; then
  for base in /opt/ZCode* /opt/zcode* /usr/lib/zcode* /usr/share/zcode* "$HOME/opt/ZCode*"; do
    hit="$(ls "$base"/resources/*/zcode.cjs 2>/dev/null | head -n1 || true)"
    if [[ -n "$hit" ]]; then ZCODE_CJS="$hit"; ZCODE_BIN="${hit%/resources*}/zcode"; break; fi
  done
else
  # Windows（含 Git Bash / MSYS）：定位后手动创建 zcode.cmd
  for base in "$LOCALAPPDATA/Programs/ZCode" "/c/Program Files/ZCode"; do
    hit="$(ls "$base"/resources/*/zcode.cjs 2>/dev/null | head -n1 || true)"
    [[ -n "$hit" ]] && ZCODE_CJS="$hit" && ZCODE_BIN="$base/ZCode.exe" && break
  done
  if [[ -n "$ZCODE_CJS" ]]; then
    echo "Windows 检测到 ZCode。请手动创建 %USERPROFILE%\\bin\\zcode.cmd："
    echo "  @echo off"
    echo "  set ELECTRON_RUN_AS_NODE=1"
    echo "  \"$ZCODE_BIN\" \"${ZCODE_CJS//\\//}\" %*"
    exit 0
  fi
  echo "错误：未找到 ZCode。请确认安装位置后手动创建 zcode.cmd。" >&2
  exit 1
fi

if [[ -z "$ZCODE_CJS" || ! -f "$ZCODE_CJS" ]]; then
  echo "错误：未找到 zcode.cjs。请确认已安装 ZCode 桌面 App（macOS: /Applications/ZCode.app）。" >&2
  exit 1
fi
if [[ ! -x "$ZCODE_BIN" ]]; then
  echo "错误：未找到 ZCode 可执行文件 $ZCODE_BIN" >&2
  exit 1
fi
echo "    找到: $ZCODE_CJS"

echo "==> 2/4 写入 wrapper: $WRAPPER"
mkdir -p "$BIN_DIR"
if [[ -e "$WRAPPER" && ! -f "$WRAPPER" ]]; then
  echo "错误：$WRAPPER 已存在且不是普通文件，请手动处理。" >&2
  exit 1
fi
cat > "$WRAPPER" <<EOF
#!/bin/sh
# generated by zcode-for-agents install.sh
ELECTRON_RUN_AS_NODE=1 exec "$ZCODE_BIN" "$ZCODE_CJS" "\$@"
EOF
chmod +x "$WRAPPER"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) echo "提示：$BIN_DIR 不在 PATH 中。请将其加入 shell 配置，例如："
     echo '      echo '\''export PATH="$HOME/.local/bin:$PATH"'\'' >> ~/.zshrc && source ~/.zshrc' ;;
esac

strip_pointers() {
  local file="$1"
  [[ -f "$file" ]] || return 0
  awk -v s="$MARKER_START" -v e="$MARKER_END" '
    $0 ~ s {skip=1; next}
    $0 ~ e {skip=0; next}
    !skip {print}
  ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
}

append_pointers() {
  local file="$1"
  [[ -f "$file" ]] || { echo "    跳过（不存在）: $file"; return 0; }
  if grep -qF "$MARKER_START" "$file"; then
    strip_pointers "$file"
    echo "    已更新既有指针段: $file"
  else
    printf '\n' >> "$file"
    echo "    已注入指针段: $file"
  fi
  cat >> "$file" <<EOF
$MARKER_START
## Using ZCode (skill: use-zcode)

本机已安装 ZCode（GLM 编码代理）。当用户提到 ZCode，或任务适合委派（浏览器/桌面自动化、Word/PPT/Excel/PDF 文档生成、定时任务、并行子任务）时，把任务委托给它：

\`\`\`sh
zcode -p "<任务描述：目标、约束、涉及文件、期望产出路径，一次给全>" --cwd <目录> --json
\`\`\`

审查类任务加 \`--mode plan\`；长任务调大超时或后台运行；续接会话用 \`--resume <sess_...>\`。详细用法见 use-zcode skill。
$MARKER_END
EOF
}

echo "==> 3/4 生成 headless 模型配置 (~/.zcode/cli/config.json)"
# headless CLI 与桌面 App 的模型配置是两套独立入口（桌面在 ~/.zcode/v2/config.json，
# CLI 在 ~/.zcode/cli/config.json），且 `zcode login` 的 OAuth 流程存在已知 bug
# （zai-org/feedback#51）。这里从桌面配置复用 coding-plan key 生成 CLI 配置。
CLI_CONFIG="${HOME}/.zcode/cli/config.json"
V2_CONFIG="${HOME}/.zcode/v2/config.json"
if [[ -f "$CLI_CONFIG" ]]; then
  echo "    已存在，跳过（不覆盖用户已有模型配置）"
elif [[ ! -f "$V2_CONFIG" ]]; then
  echo "    跳过：未找到桌面配置 $V2_CONFIG（请先打开 ZCode 桌面 App 登录，再运行本脚本）"
elif ! command -v jq >/dev/null 2>&1; then
  echo "    跳过：未安装 jq（brew install jq 后重跑本步骤）"
else
  PKEY="$(jq -r '.provider["builtin:bigmodel-coding-plan"].options.apiKey // empty' "$V2_CONFIG" 2>/dev/null)"
  PBASE="https://open.bigmodel.cn/api/anthropic"
  if [[ -z "$PKEY" ]]; then
    PKEY="$(jq -r '.provider["builtin:zai-coding-plan"].options.apiKey // empty' "$V2_CONFIG" 2>/dev/null)"
    PBASE="https://api.z.ai/api/anthropic"
  fi
  if [[ -z "$PKEY" ]]; then
    echo "    跳过：桌面配置中无可用的 coding-plan API key"
  else
    umask 077
    jq -n --arg key "$PKEY" --arg base "$PBASE" \
      '{provider: {bigmodel: {kind: "anthropic", name: "BigModel Coding Plan",
         options: {apiKeyRequired: true, baseURL: $base, apiKey: $key},
         models: {"glm-5.3-flash": {name: "GLM-5.3-Flash"}}}},
       model: {main: "bigmodel/glm-5.3-flash", lite: "bigmodel/glm-5.3-flash"}}' > "$CLI_CONFIG"
    echo "    已写入 ${CLI_CONFIG} （复用桌面端 coding-plan key，权限 600）"
  fi
fi

echo "==> 4/4 注入指针段"
if [[ "$WITH_POINTERS" -eq 1 ]]; then
  append_pointers "${HOME}/.codex/AGENTS.md"
  append_pointers "${HOME}/.claude/CLAUDE.md"
else
  echo "    已按 --no-pointers 跳过"
fi

echo "==> 验证"
if "$WRAPPER" version >/dev/null 2>&1; then
  echo "    zcode wrapper OK: $($WRAPPER version 2>&1 | head -n1)"
else
  echo "警告：wrapper 无法运行 'zcode version'，请手动检查：$WRAPPER version" >&2
fi

cat <<'EOF'

完成。剩余步骤（skill 分发，任选其一）：

  npx skills add dej4vu/zcode-for-agents -g     # 推荐：vercel-labs/skills，自动软链到各 agent 目录
  # 或手动：ln -s <本仓库>/skills/use-zcode ~/.agents/skills/use-zcode

卸载：bash uninstall.sh && npx skills remove use-zcode -g
EOF
